openapi: 3.0.0
info:
  description: this is a restful api of dtp
  title: nirvana
  version: 1.0.0
servers:
- url: http://0.0.0.0:9090/api/
  description: 本地调试环境
- url: http://10.10.130.100:9090/api/
  description: 测试环境
tags:
- description: everything about user
  name: user
- description: everything about namespace
  name: namespaces
- description: everything about project
  name: project


paths:
  /login:
    post:
      summary: 登陆
      operationId: openapi.api.user.login
      description: 登陆
      tags:
      - user
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: 登陆成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
  /register:
    post:
      summary: 注册新用户
      operationId: openapi.api.user.register
      description: 注册新用户
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
  /namespaces:
    get:
      tags:
      - namespaces
      summary: 获取namespace列表
      operationId: openapi.api.namespace.list
      parameters:
      - name: token
        in: header
        description: 用户的token令牌
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 返回namespace和project的聚合结构
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Namespace'

    post:
      tags:
      - namespaces
      summary: 创建namespace
      operationId: openapi.api.namespace.create
      parameters:
      - name: token
        in: header
        description: 用户的token令牌
        required: true
        schema:
          type: string
      requestBody:
        description: 创建命名空间传名称和描述
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/NamespaceBody'
        required: true
      responses:
        200:
          description: ''
  /namespaces/{namespace_id}:
    delete:
      tags:
      - namespaces
      summary: 删除命名空间
      operationId: openapi.api.namespace.delete
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace_id
        in: path
        description: 命名空间id
        required: true
        schema:
          type: string
      responses:
        200:
          description: ''
  /project:
    post:
      tags:
      - project
      summary: 创建项目
      operationId: openapi.api.project.create
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      requestBody:
        description: 项目信息前端传什么存什么
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/ProjectBody'
        required: true
      responses:
        200:
          description: successful operation
  /project/{project_id}:
    get:
      tags:
      - project
      summary: 获取指定项目的内容
      operationId: openapi.api.project.detail
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        description: 项目id
        required: true
        schema:
          type: string
      responses:
        200:
          description: 返回项目信息前端传什么返回什么
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ProjectBody'

    put:
      tags:
      - project
      summary: 更新指定项目的内容
      operationId: openapi.api.project.update
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        description: 项目id
        required: true
        schema:
          type: string
      requestBody:
        description: 更新项目
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/ProjectBody'
      responses:
        200:
          description: ''

    delete:
      tags:
      - project
      summary: 删除项目
      operationId: openapi.api.project.delete
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        description: 项目id
        required: true
        schema:
          type: string
      responses:
        200:
          description: ''

  /project/{project_id}/name:
    put:
      tags:
      - project
      summary: 修改项目的名字
      operationId: openapi.api.project.rename
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        description: 项目id
        required: true
        schema:
          type: string
      requestBody:
        description: 更新项目的名字
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: ''

  /envs:
    get:
      summary: 获取环境列表
      description: 获取环境列表
      operationId: openapi.api.env.list
      tags:
      - env
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 返回环境列表
          content:
            application/json:
              schema:
                items:
                  properties:
                    description:
                      type: string
                    env:
                      type: string
                    id:
                      type: string

    post:
      summary: 创建环境
      description: 创建环境
      operationId: openapi.api.env.create
      tags:
      - env
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                env:
                  type: string
                url:
                  type: string
                description:
                  type: string
              required:
              - env
              - url
      responses:
        200:
          description: ''

  /envs/{env_id}:
    put:
      summary: 修改环境
      description: 修改环境内容
      operationId: openapi.api.env.update
      tags:
      - env
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: env_id
        description: 环境id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                env:
                  type: string
                url:
                  type: string
                description:
                  type: string
              required:
              - env
              - url
      responses:
        200:
          description: ''

    delete:
      summary: 删除环境
      description: 根据环境id删除环境
      operationId: openapi.api.env.delete
      tags:
      - env
      parameters:
      - name: token
        in: header
        description: 用户token令牌
        required: true
        schema:
          type: string
      - name: namespace
        in: header
        description: 命名空间id
        required: true
        schema:
          type: string
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: env_id
        description: 环境id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: ''



components:
  schemas:
    NamespaceBody:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    Namespace:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    ProjectBody:
      type: object
      required:
      - tag
      - detail
      - apis
      - models
      - envs
      - scripts
      properties:
        detail:
          type: object
          description: 描述
          properties:
            info:
              type: object
              required:
              - title
              properties:
                title:
                  type: string
                description:
                  type: string
                tags:
                  type: string
            servers:
              type: array
              items:
                type: string
            tags:
              type: array
              items:
                type: string
        apis:
          type: array
          items:
            $ref: '#/components/schemas/ApiBody'
        models:
          type: array
          items:
            type: object
        envs:
          type: array
          items:
            type: object
        scripts:
          type: array
          items:
            type: object
        tag:
          type: string
        commit:
          type: string
    ApiBody:
      type: object
      properties:
        path:
          type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        params:
          type: array
          nullable: true
          items:
            type: object
        query:
          type: array
          nullable: true
          items:
            type: object
        header:
          type: array
          nullable: true
          items:
            type: object
        responseBody:
          type: array
          items:
            type: object
            example: {
              code: 200,
              description: '',
              data: {},
            }
        requestBody:
          type: string
    PutProjectBody:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        tag:
          type: string
    Project:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        tag:
          type: string