openapi: 3.0.0
info:
  description: this is a restful api of dtp
  title: nirvana
  version: v1.0
servers:
- url: http://0.0.0.0:9090/api/
  description: 本地调试环境
- url: http://10.10.130.100:9090/api/
  description: 测试环境
tags:
- description: everything about namespace
  name: namespace
- description: everything about project
  name: project
- description: everything about api
  name: api
- description: component
  name: component
- description: everythin about env
  name: env
- description: everything about global env
  name: globalenv
- description: everything about testcase
  name: case
- description: everything about testcase run
  name: test
- description: everything about script
  name: script
- description: everything about task
  name: task

paths:
  /namespaces:
    get:
      summary: 获取namespace的列表
      description: 获取namespace的列表
      operationId: openapi.api.namespace.list
      tags:
      - namespace
      parameters:
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      responses:
        '200':
          description: namespace的返回列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: string

    post:
      summary: 创建namespace
      description: 新建namespace
      operationId: openapi.api.namespace.create
      tags:
      - namespace
      parameters:
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - namespace
              properties:
                namespace:
                  type: string
                description:
                  type: string

      responses:
        '200':
          description: 创建namespace成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createsuccess'
        '400':
          description: 创建namespace失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createfailed'

  /namespaces/{namespace_id}/projects:
    get:
      summary: 获取项目列表
      description: 获取指定的namespace下的项目列表
      operationId: openapi.api.project.list
      tags:
      - project
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: version
        in: query
        description: 指定版本
        schema:
          type: string
      responses:
        '200':
          description: 返回项目列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        project:
                          type: string
                        id:
                          type: string
                        description:
                          type: string
                        url:
                          type: string

    post:
      summary: 创建项目
      description: 在指定的namespace下创建项目
      operationId: openapi.api.project.create
      tags:
      - project
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
              properties:
                title:
                  type: string
                description:
                  type: string
                version:
                  type: string
      responses:
        '200':
          description: 创建项目成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createsuccess'
        '400':
          description: 创建项目失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createfailed'

  /namespaces/{namespace_id}/projects/{project_id}:
    put:
      summary: 更新项目
      description: 在指定的namespace下更新项目
      operationId: openapi.api.project.update
      tags:
      - project
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: project的id
        in: path
        name: project_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
              properties:
                title:
                  type: string
                description:
                  type: string
                version:
                  type: string
      responses:
        '200':
          description: 更新项目成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatesuccess'
        '400':
          description: 更新项目失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatefailed'

    delete:
      summary: 删除项目
      description: 删除指定的项目
      operationId: openapi.api.project.delete
      tags:
      - project
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: project的id
        in: path
        name: project_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 删除项目成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletesuccess'
        '400':
          description: 删除项目失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletefailed'

  /namespaces/{namespace_id}/projects/{project_id}/apis:
    get:
      summary: 获取项目下的接口列表
      description: 获取指定项目下的接口列表
      operationId: openapi.api.api.list
      tags:
      - api
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 返回接口列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        project:
                          type: string
                        id:
                          type: string
                        description:
                          type: string
                        url:
                          type: string
    post:
      summary: 获取项目下的接口列表
      description: 获取指定项目下的接口列表
      operationId: openapi.api.api.create
      tags:
      - api
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_content:
                  type: object
      responses:
        '200':
          description: 创建接口成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createsuccess'
        '400':
          description: 创建接口失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createfailed'

  /namespaces/{namespace_id}/projects/{project_id}/apis/{api_id}:
    get:
      summary: 获取项目下的接口列表
      description: 获取指定项目下的接口列表
      operationId: openapi.api.api.detail
      tags:
      - api
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: api_id
        in: path
        description: api的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 返回接口列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        project:
                          type: string
                        id:
                          type: string
                        description:
                          type: string
                        url:
                          type: string
    put:
      summary: 更新指定接口
      description: 更新指定接口的内容
      operationId: openapi.api.api.update
      tags:
      - api
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: api_id
        in: path
        description: api的id
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_content:
                  type: object
      responses:
        '200':
          description: 更新项目成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatesuccess'
        '400':
          description: 更新项目失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatefailed'
    delete:
      summary: 删除指定接口
      description: 删除指定接
      operationId: openapi.api.api.delete
      tags:
      - api
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: api_id
        in: path
        description: api的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 删除接口成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletesuccess'
        '400':
          description: 删除接口失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletefailed'
  /namespaces/{namespace_id}/projects/{project_id}/components:
    get:
      summary: 获取项目下的components列表
      description: 获取项目下的components列表
      operationId: openapi.api.component.list
      tags:
      - component
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 返回component列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        component_content:
                          type: string
                        id:
                          type: string
                        type:
                          type: string
                        uid:
                          type: string
    post:
      summary: 创建component
      description: 创建component
      operationId: openapi.api.component.create
      tags:
      - component
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                component_content:
                  type: object
                type:
                  type: string
      responses:
        '200':
          description: 创建component成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createsuccess'
        '400':
          description: 创建component失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createfailed'

  /namespaces/{namespace_id}/projects/{project_id}/components/{component_id}:
    get:
      summary: 获取components详情
      description: 获取components详情
      operationId: openapi.api.component.detail
      tags:
      - component
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: component_id
        in: path
        description: component的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 返回component的详情
          content:
            application/json:
              schema:
                type: object
                properties:
                    component_content:
                      type: string
                    id:
                      type: string
                    type:
                      type: string
                    uid:
                      type: string
    put:
      summary: 更新components详情
      description: 更新components详情
      operationId: openapi.api.component.update
      tags:
      - component
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: component_id
        in: path
        description: component的id
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                component_content:
                  type: object
      responses:
        '200':
          description: 更新component成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatesuccess'
        '400':
          description: 更新component失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatefailed'
    delete:
      summary: 删除components
      description: 删除components
      operationId: openapi.api.component.delete
      tags:
      - component
      parameters:
      - description: namespace的id
        in: path
        name: namespace_id
        schema:
          type: string
        required: true
      - description: 操作人
        in: header
        name: user
        schema:
          type: string
        required: true
      - name: project_id
        in: path
        description: project的id
        schema:
          type: string
        required: true
      - name: component_id
        in: path
        description: component的id
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 删除component成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletesuccess'
        '400':
          description: 删除component失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletefailed'

components:
  schemas:
    createsuccess:
      type: object
      properties:
        title:
         type: string
         example: "创建xx成功"
    createfailed:
      type: object
      properties:
        title:
          type: string
          example: "创建xx失败"
    updatesuccess:
      type: object
      properties:
        title:
          type: string
          example: "更新xx成功"
    updatefailed:
      type: object
      properties:
        title:
          type: string
          example: "更新xx失败"
    deletesuccess:
      type: object
      properties:
        title:
          type: string
          example: "xx已删除"
    deletefailed:
      type: object
      properties:
        title:
          type: string
          example: "删除xx失败"